### ISSUE TITLE
Which version of TaggerOne is this based on ?

### ISSUE THREAD

**Issue by behrica** [anarkia7115/TaggerOne#2]
I am currently using TaggerOne version 0.2.1 as downloadable from here:
https://www.ncbi.nlm.nih.gov/research/bionlp/taggerone/TaggerOne-0.2.1.tgz

I hit a problem of an "endless loop" related to the abreviations and this might be just teh issue you have fixed. So I want to try your version here.

I just wanted to be sure, what "official" version yout code is based on.

**Comment by anarkia7115** [comment]
Hi, behrica. The this repo is not official. The source is downloaded from [TaggerOne-0.2.1.tgz](https://www.ncbi.nlm.nih.gov/research/bionlp/taggerone/TaggerOne-0.2.1.tgz) as you have provided. 

If there's other questions please feel free to reopen it. 

Thank you.

**Comment by behrica** [comment]
We want to use "your version" of TaggerOne in a systematic literature review
and probably want somehow refer to it. (Github would be fine)
As I was hitting the same issue as you, we cannot use the "official" version 0.2.1

I think it would be in the interest of everybody, that this bug in TaggerOne 0.2.1 gets fixed.
I reported the issue as well at the "maybe" official Github repo (even though there is no code):

https://github.com/ncbi-nlp/TaggerOne/issues/1

Currently I would need to "refer" to two thinks in order to make out work reproducible (which is required).

- The code being here.
- The pre-trained model to be inside https://www.ncbi.nlm.nih.gov/research/bionlp/taggerone/TaggerOne-0.2.1.tgz

which is not ideal.
