### ISSUE TITLE
make a relesase, 2.1.1 ?

### ISSUE THREAD

**Issue by behrica** [anarkia7115/TaggerOne#7]
Should I do a release 2.1.1,
and adding a little CHANGES.md file ?

I think I finished to use TaggerOne for my current project,
and would like to refer cleanly to the version I have used.

**Comment by anarkia7115** [comment]
Of course. 
Feel free to make a release and add a CHANGES.md file.

**Comment by behrica** [comment]
I did 0.2.2 at the end
